### ISSUE TITLE
PHP-CS-Fixer v3

### ISSUE THREAD

**Issue by fabiiomiiguel** [mansoorkhan96/php-cs-fixer#1]
Incompatibility with the new version of php-cs-fixer.

**Comment by mansoorkhan96** [comment]
@fabiiomiiguel I have tried to reproduce this and it works for me.
This is how you can override default php-cs-fixer file.
```json
"php-cs-fixer.toolPath": "C:\\Users\\Jawad\\.vscode\\php-cs-fixer-v3.phar",
```

What are you trying to do?

**Comment by mansoorkhan96** [comment]
I have added the latest version of v3 🤩😎

**Comment by fabiiomiiguel** [comment]
I was just adding a custom file of configs. I didn't try the custom phar. But thank you for updating that, you rock.

**Comment by mansoorkhan96** [comment]
@fabiiomiiguel great
It would appropriate if you could star the repo and write feedback on the [extension marketplace](https://marketplace.visualstudio.com/items?itemName=mansoorkhan96.php-cs-fixer)

**Comment by fabiiomiiguel** [comment]
Done 😉
