### ISSUE TITLE
How to set the path

### ISSUE THREAD

**Issue by maofree** [mansoorkhan96/php-cs-fixer#19]
Hi

I don't know how to set the path to php-cs-fixer file

following this suggestion:
Open settings.json file (Ctrl + Shift + P) and add the following setting:
"php-cs-fixer.toolPath": "path\\php-cs-fixer.phar",

if I push (Ctrl + Shift + P) I cannot set this line (llok at the image)

"php-cs-fixer.toolPath": "/usr/local/bin/php-cs-fixer",

![11](https://user-images.githubusercontent.com/653230/232743328-da6259ef-ce9f-4ce8-8350-cc89d98b4b2e.png)

I've used the globally solution on my local debian server (I use sftp)
https://cs.symfony.com/doc/installation.html

wget https://cs.symfony.com/download/php-cs-fixer-v3.phar -O php-cs-fixer
sudo chmod a+x php-cs-fixer
sudo mv php-cs-fixer /usr/local/bin/php-cs-fixer

![111](https://user-images.githubusercontent.com/653230/232744681-6dc3d2ef-191d-46cf-9a6c-62d04d06ec78.png)
I tried to set /usr/local/bin/php-cs-fixer  here but I get an error during the formatting

can you help me how to use your extension?

thanks

**Comment by maofree** [comment]
I've seen that the 3.15.1 is used inside the extension but If I select it to do the "format document" nothing happens

**Comment by mansoorkhan96** [comment]
`Ctrl + Shift + P` or `Cmd + Shift + P` opens up command palette. Then you need to type `settings.json` in prompt input and it would show suggestions. Click on settings.json file and it should open it.

<img width="661" alt="image" src="https://user-images.githubusercontent.com/51432274/236193421-a05f1985-55e2-41fe-987e-a997cc9b5469.png">

**Comment by mansoorkhan96** [comment]
Another option would be open the extension page, click on Cog icon and then click on Extension settings option.
Once you are on extension settings page, you should be able to see a config to set the path.

<img width="783" alt="image" src="https://user-images.githubusercontent.com/51432274/236193858-6159a200-1713-4bfd-8162-2d336173e4ef.png">
