### ISSUE TITLE
Add the ability to disable formatting when saving a document

### ISSUE THREAD

**Issue by Leonid74** [mansoorkhan96/php-cs-fixer#26]
It would be great if you added the ability to disable formatting when saving a document.

**Comment by mansoorkhan96** [comment]
You can just comment out the line `"editor.defaultFormatter": "mansoorkhan96.php-cs-fixer"` in your settings.json.

**Comment by radoslav-grencik** [comment]
Sorry but the last version is downgrade, there was an option called ```php-cs-fixer.fixOnSave``` which disabled formatting on auto save which I do not want and it was great. Now the option is gone and I don`t understand why. I want to have ability to format only on my explicit save (ctrl + s). Please bring the option back, the extension is great. Thank you!

**Comment by mansoorkhan96** [comment]
I am adding it back.
But this was mainly for old versions when you did not have option `editor.defaultFormatter`. But now it forces you to have it setup to format files so did not make sense to keep the fixOnSave. Atleast thats how it has been working for me on Mac.

Anyways, i am adding the option back as it was.

**Comment by radoslav-grencik** [comment]
Yeah I am Windows (WSL2) user, maybe it works differently. Thank you!

**Comment by mansoorkhan96** [comment]
@radoslav-grencik Fix on save is back. can you please confirm the latest version works as expected on your side?

**Comment by radoslav-grencik** [comment]
Yes it is working as expected.
