### ISSUE TITLE
How to use the extension with Docker?

### ISSUE THREAD

**Issue by diosby** [mansoorkhan96/php-cs-fixer#3]
Hello!
I want to run the fixer from a docker container, but if I set `docker-compose exec -T container-name vendor/bin/phing php-cs-fixer` in **Tool path** it doesn't work.

Can I change a path of environment or a path to run the fixer from the container? 
Thanks.

**Comment by mansoorkhan96** [comment]
`toolPath` config option expects complete path to fixer file (.phar file).

something like this in your `settings.json` file:

```json
"php-cs-fixer.toolPath": "path\\php-cs-fixer.phar",
```

**Comment by abbluiz** [comment]
You should have a PHP executable accessible outside Docker for it to work.

**Comment by mansoorkhan96** [comment]
I am closing this issue for now, as there is no active discussion on this.
