### ISSUE TITLE
Update PHP-CS-FIXER to v3.4.0 (or newer) to support PHP 8.1

### ISSUE THREAD

**Issue by abbluiz** [mansoorkhan96/php-cs-fixer#4]
New releases of PHP-CS-FIXER have come out, including v3.4.0, which supports PHP 8.1. 

https://github.com/FriendsOfPHP/PHP-CS-Fixer

**Comment by abbluiz** [comment]
I guess I'll use a custom php-cs-fixer file for now.

**Comment by mansoorkhan96** [comment]
> New releases of PHP-CS-FIXER have come out, including v3.4.0, which supports PHP 8.1.
> 
> https://github.com/FriendsOfPHP/PHP-CS-Fixer

Hey, @abbluiz 
I will update it soon :)

**Comment by mansoorkhan96** [comment]
> New releases of PHP-CS-FIXER have come out, including v3.4.0, which supports PHP 8.1.
> 
> https://github.com/FriendsOfPHP/PHP-CS-Fixer

I have updated the PHP CS Fixer to `v3.6.0`
