### ISSUE TITLE
Error executing with new VS Code update

### ISSUE THREAD

**Issue by davidkoh83** [mansoorkhan96/php-cs-fixer#5]
It seems that the extension cannot run with the latest version of VSCode that came out a few days ago

**Comment by mansoorkhan96** [comment]
> It seems that the extension cannot run with the latest version of VSCode that came out a few days ago

Hey,
I am running `Vscode version 1.64` and everything seems to be working for me.
Do you get any error or warning or anything in the console that can help me understand the issue?

**Comment by davidkoh83** [comment]
I am running v1.64 as well. Whenever I run it, it says "There was an error while running php-cs-fixer. Check the Developer Tools console for more information."
The Debug Console is empty

**Comment by davidkoh83** [comment]
Sorry. I just found out the reason. Apparently my custom setting file was deleted when VSCode updated because I placed it in the same folder as VSCode!
Sorry to take up your time and keep up the good work!
